baseURL: "https://miumiu-op.github.io/"
title: "Follow Miaomiao"
theme: hugo-profile
favicon: "/static/favicon.ico"

defaultContentLanguage: en

languages:
  zh:
    languageName: "简体中文"
    languageCode: "zh-cn"
    contentDir: "content/zh"
    weight: 2
    title: "关注 Miaomiao" # 中文版的标题
    menu:
      main:
        - identifier: about
          name: "关于我"
          url: "/zh/#about"        # 手动锁定中文路径
          weight: 1
        - identifier: experience
          name: "工作经验"
          url: "/zh/#experience"   # 手动锁定中文路径
          weight: 2
        - identifier: education
          name: "教育背景"
          url: "/zh/#education"    # 手动锁定中文路径
          weight: 3
        - identifier: achievements
          name: "个人成就"
          url: "/zh/#achievements" # 手动锁定中文路径
          weight: 4
        - identifier: blog
          name: 博客
          title: 博文
          url: /zh/blogs
          weight: 10
        # - identifier: gallery
        #   name: 图集
        #   title: 博文
        #   url: /gallery
        #   weight: 2
        #Dropdown menu
        - identifier: dropdown
          title: 示例下拉菜单
          name: 作品集
          weight: 7
        - identifier: dropdown1
          title: 示例下拉菜单 1
          name: 软件文档
          url: "/zh/portfolio/software/"
          parent: dropdown
          weight: 1
        - identifier: dropdown2
          title: 示例下拉菜单 2
          name: 开发者文档
          url: "/zh/portfolio/developer/"
          parent: dropdown
          weight: 2
        - identifier: lang-switch
          pre: '<i class="fa fa-globe"></i>'
          name: "English"      # 这里的文字就是你的 UI 按钮
          url: "/"
          weight: 100         # 权重设大一点，让它排在导航栏最后面
    params:
      title: "关注 Miaomiao"
      description: "Miaomiao Pan 的个人站点"
      navbar:
        brandName: "关注 Miaomiao"
        menus:
          disableAbout: true        # 禁用自动生成的“关于我”
          disableExperience: true   # 禁用自动生成的“工作经验”
          disableEducation: true    # 禁用自动生成的“教育背景”
          disableAchievements: true # 禁用自动生成的“个人成就”
          disableProjects: true
          disableContact: true
      hero:
        intro: "你好，我是"
        title: "Miaomiao"
        subtitle: "人生短暂，但工作可以让它变漫长"
        content: "我不太喜欢标签，但如果需要，我会说自己是技术写作者、INFJ，以及 KPop 爱好者。"
        button:
          name: "联系我"
      about:
        title: "关于我"
        content: |-
          你好，我是 Miaomiao Pan，你也可以叫我 Miumiu——这是朋友们常用的称呼。

          过去几年，我深耕技术写作领域，专注于面向用户的内容创作，包括技术文档的撰写与翻译、UI 文案，以及视频脚本。

          我尤其关注 AI 驱动的文档工程与自动化工具在流程优化中的应用，并成功落地相关实践，提升效率与生产力。
        skills:
          title: "以下是我掌握的一些技能："
          items:
            - "AI 与自动化：提示工程、Cursor、Windsurf、n8n、Python"
            - "内容技术栈：DITA（Oxygen、IXIA CCMS）、Markdown、XML/HTML、API 文档"
            - "协作与设计：Git、Jira、VS Code、Figma、Snagit"
      experience:
        title: "工作经验"
        items:
          - job: "技术写作者"
            company: "Cobo"
            date: "2024.06 - 至今"
            content: |
              在 Cobo，我负责 Custody/WaaS 业务线的文档工作，确保全覆盖并快速迭代。主要贡献包括：

              - 主导交付 13 万字的双语《数字资产安全手册》。
              - 借助 AI 与数据分析提升开发者体验与文档效率。
              - 开发自动化机器人（Slack、n8n）以优化用户反馈与内容流程。
          - job: "技术写作者"
            company: "Agora"
            date: "2022.05 - 2023.07"
            content: |
              在 Agora.io（即声网）期间，我负责双语发布说明与 API 文档，并优化协作流程。除此之外，我还：

              - 使用 ChatGPT 编写 Python 自动化脚本，用于语法检查、样式更新与文件生成。
              - 引入 Jira 规范协作流程，提升任务跟踪效率。
              - 优化 API 文档工具链与 XML 转 JSON 转换逻辑。
          - job: "用户帮助开发者"
            company: "SAP"
            date: "2019.11 - 2022.05"
            content: |
              在 SAP 任职期间，我与产品经理和工程师协作，产出面向客户的内容。除此之外，我还：

              - 编写跨产品功能的集成指南。
              - 协助本地团队引入 Jira，提高团队效率。
              - 使用 Snagit 制作演示视频，降低用户学习成本。
          - job: "技术写作者"
            company: "KUKA Robotics"
            date: "2019.04 - 2019.11"
            content: |
              与产品经理和工程师协作交付基于 DITA 的机器人操作系统文档，负责翻译供应商管理与质量审查，并完成机器人操作系统相关培训。
      education:
        title: "教育背景"
        items:
          - title: "翻译硕士"
            school:
              name: "上海外国语大学"
            date: "2016 - 2019"
            content: "英汉翻译"
          - title: "工商管理学士"
            school:
              name: "浙江工商大学"
            date: "2012 - 2016"
            content: "工商管理"
      achievements:
        title: "个人成就"
        items:
          - title: "行业贡献"
            content: "Infomagic（TC 互联）技术传播社区讲师 & 技术传播专业委员会成员。"
          - title: "语言证书"
            content: "雅思 7.5，CET-6（564），CET-4（596），全国大学生英语竞赛一等奖。"
          - title: "在线学习证书"
            content: "完成多项在线课程，包括 Kaggle SQL 入门、EA 软件工程虚拟体验项目、Postman API Fundamentals Student Expert 等。"
      footer:
        recentPosts:
          title: "最新文章"
      terms:
        read: "阅读"
        toc: "目录"
        copyright: "版权所有"
        pageNotFound: "页面未找到"
        emailText: "查看此网站"
  en:
    languageName: "English"
    languageCode: "en-us"
    contentDir: "content/en"
    weight: 1
    title: "Follow Miaomiao" # 英文版的标题
    menu:
      main:
        - identifier: blog
          name: Blog
          title: Blog posts
          url: /blogs
          weight: 2
        # - identifier: gallery
        #   name: Gallery
        #   title: Blog posts
        #   url: /gallery
        #   weight: 2
        #Dropdown menu
        - identifier: dropdown
          title: Example dropdown menu
          name: Portfolio
          weight: 1
        - identifier: dropdown1
          title: example dropdown 1
          name: Software Documentation
          url: "/portfolio/software/"
          parent: dropdown
          weight: 1
        - identifier: dropdown2
          title: example dropdown 2
          name: Developer Documentation
          url: "/portfolio/developer/"
          parent: dropdown
          weight: 2
        - identifier: lang-switch
          pre: '<i class="fa fa-globe"></i>'
          name: "简体中文"      # 这里的文字就是你的 UI 按钮
          url: "/zh/"
          weight: 100         # 权重设大一点，让它排在导航栏最后面

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-D2FL1SEN1Q

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Follow Miaomiao"
  description: "A cool site of Miaomiao Pan"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Follow Miaomiao" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, this is"
    title: "Miaomiao"
    subtitle: "Life is short but work can make it longer"
    content: "Not a big fan of labels, but if necessary, I'd identify as a technical writer, an INFJ personality type, and a KPop lover."
    image: /images/me.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Contact Me"
      url: "mailto:miaomiao_pan@163.com"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/miaomiao-pan-19013b141/
        - icon: fab fa-github
          url: https://github.com/miumiu-op/miumiu-op.github.io

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      Hello, I’m Miaomiao Pan, but you can call me Miumiu—it’s what my friends usually go with. 
      
      Over the past several years, I've immersed myself in the world of technical writing, focusing on user-oriented content creation. My experience includes writing and translating technical documents, crafting UI text, and scripting videos.

      I'm particularly passionate about AI-driven documentation engineering and leveraging automation tools to enhance workflow efficiency. I've successfully implemented such initiatives to streamline processes and improve productivity.
    skills:
      enable: true
      title: "Here are a few skills I've mastered:"
      items:
        - "AI & Automation: Prompt Engineering, Cursor, Windsurf, n8n, Python"
        - "Content Tech Stack: DITA (Oxygen, IXIA CCMS), Markdown, XML/HTML, API Docs"
        - "Collaboration & Design: Git, Jira, VS Code, Figma, Snagit"

  # Experience
  experience:
    enable: true
    title: "Working Experience"
    items:
      - job: "Technical Writer"
        company: "Cobo"
        companyUrl: "https://www.cobo.com"
        date: "Jun 2024 - Present"
        info:
          enable: true
        content: |
          At Cobo, I led the documentation for the Custody/WaaS business line, ensuring full coverage and rapid iteration. Key contributions include:

          - Orchestrated the delivery of a 130,000-word bilingual Digital Asset Security Manual.
          - Leveraged AI and data analysis to optimize developer experience and documentation efficiency.
          - Developed automation bots (Slack, n8n) to streamline user feedback and content processes.

      - job: "Technical Writer"
        company: "Agora"
        companyUrl: "https://www.agora.io"
        date: "May 2022 - Jul 2023"
        info:
          enable: true
        content: |
          At Agora.io (aka Shengwang), I managed bilingual release notes and API documentation while optimizing workflows. Besides, I also:

          - Developed Python automation scripts using ChatGPT for grammar checks, style updates, and file creation.
          - Standardized collaboration processes by introducing Jira for task tracking.
          - Optimized the API documentation toolchain and XML-to-JSON conversion logic.

      - job: "User Assistance Developer"
        company: "SAP"
        companyUrl: "https://www.sap.com"
        date: "Nov 2019 - May 2022"
        info:
          enable: true
        content: |
          At SAP, I worked as a user assistance developer, collaborating with product management and engineers to generate customer-facing content. Besides, I also:

          - Authored integration guides for complex cross-product features.
          - Assisted the local team in integrating Jira, boosting team efficiency.
          - Produced demonstration videos using Snagit to reduce user learning costs.

      - job: "Technical Writer"
        company: "KUKA Robotics"
        companyUrl: "https://www.kuka.com"
        date: "Apr 2019 - Nov 2019"
        info:
          enable: true
        content:
          "Collaborated with product managers and engineers to deliver DITA-based documentation for robot operating systems. I managed translation vendors, conducted quality audits, and completed comprehensive training in robot OS fundamentals."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Translation"
        school:
          name: "Shanghai International Studies University in Shanghai, China"
          url: "http://www.shisu.edu.cn/"
        date: "2016 - 2019"
        content: "English-Chinese Translation"
      - title: "Bachelor of Business Administration"
        school:
          name: "Zhejiang Gongshang University in Hangzhou, China"
          url: "http://www.zjgsu.edu.cn/"
        date: "2012 - 2016"
        content: "Business Administration"


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Industry Contribution
        content: Infomagic (TC Hulian) Technical Communication Community Instructor & Technical Communication Professional Committee Member.
      - title: Language Certificates
        content: IELTS 7.5, CET-6 (564), CET-4 (596), and First Prize in National English Competition for College Students.
      - title: Online Learning Certificates
        content: I completed multiple online learning programs, including Intro to SQL by Kaggle, Software Engineering Virtual Experience Program by EA, Postman API Fundamentals Student Expert, etc.

  # projects
  # projects:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Follow Miaomiao
  #       content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
  #       image: /images/projects/profile.png
  #       featured:
  #         name: Demo
  #         link: https://hugo-profile.netlify.app
  #       badges:
  #         - "Hugo"
  #         - "Bootstrap"
  #         - "Javascript"
  #       links:
  #         - icon: fa fa-envelope
  #           url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
  #         - icon: fab fa-github
  #           url: https://github.com/gurusabarish/hugo-profile
  #         - icon: fab fa-twitter
  #           url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
